# Site Build Settings

url: https://25scripture.pages.gwdg.de

# jekyll-paginate configuration
paginate: 50
# Collections for podcast and RSS feeds
collections:
  podcasts:
    output: true
    permalink: /:collection/:title

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
plugins:
  [
    jekyll-paginate,
    jekyll-sitemap,
    jekyll-feed,
    jekyll-seo-tag,
    jekyll-include-cache,
  ]
future: true

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Making Scripture"
description:	       "Hands-on experiments to understand the physical production of premodern texts (course website, summer semester 2025)"
author:              "Nathan Gibson"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml

hide_related_posts: false
hide_post_share: true
